server:
  port: 8081
#  servlet:
#    context-path: /myproject

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myuploader?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jarvish.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl